# get rabbitmq management docker image
FROM rabbitmq:3-management

# run inside a pulled default RabbitMQ Docker container to see where the files are located
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
COPY definitions.json /etc/rabbitmq/definitions.json




